Mubarak
Content-Creater-Platform/CCP-Contract pull request #31
Opened 2024-05-06 01:34 UTC by MubarakOke

2024-05-06 09:36 UTC, VictoriaAde requested changes

2024-05-06 09:36 UTC, VictoriaAde commented on frontend-material/txt.txt
@MubarakOke The frontend is still using the previously verified address that you removed. 
Please add them back, you can add comments to differentiate them from the new addresses - v1 or v2.

2024-05-06 12:15 UTC, VictoriaAde requested changes

2024-05-06 12:15 UTC, VictoriaAde commented on src/DAO.sol
@Adecom16 We are now making use of CCP2, please make use of that instead.

2024-05-06 12:41 UTC, Adecom16 commented on src/DAO.sol
alright

2024-05-07 12:35 UTC, closed without merging

2024-05-07 12:37 UTC, VictoriaAde commented
I am closing this PR because a lot things aren't right.

@MubarakOke  @Adecom16.
Please make the PR again, this time in separate branches.
Please take note of the addresses, we are still using the addresses for the CCP1 version.
Right now, we should have two versions of addresses, CCP1 and CCP2, take note of that.